query ViewApplicationStatus($id: ObjectId!, $token: String!) {
  viewApplicationStatus(id: $id, token: $token) {
    status
    emailVerified
    socialsAdded
    requiresArt
    artUploaded
    links
    instagram
    twitter
  }
}