query GetConceptNFTs($offset: Int, $limit: Int) {
  getConceptNFTs(offset: $offset, limit: $limit) {
    nfts {
      id
      status
      stage
      edit {
        info
        collection
        media
        token
      }
      info {
        title
        description
        link
        nsfw
        ai
        aiDescription
        tags
      }
      token {
        unitName
        assetName
        royalty
        editions
      }
      artist {
        id
        address
        name
        normalizedName
        profileImage {
          cid
          mimeType
          previews {
            size
            cid
            mimeType
          }
        }
      }
      c {
        id
        title
        attributes {
          traitType
          value
          displayType
        }
      }
      card {
        x
        y
        type
      }
      media {
        fileroomId
        cid
        dimensions
        storageSize
        mimeType
        integrity
        previews {
          size
          cid
          mimeType
          integrity
        }
        thumbnail {
          cid
          mimeType
          previews {
            cid
            mimeType
            size
          }
        }
      }
    }
    pageInfo {
      totalDocs
      offset
      limit
      totalPages
      page
      hasPrevPage
      hasNextPage
      prevPage
      nextPage
    }
  }
}