query GetExtractFixedBidParams($settings: [ExtractFixedBidParams!]!) {
  getExtractFixedBidParams(settings: $settings) {
    description
    blob
    txID
    signers
    signature
    authAddress
  }
}