query GetUpdatePriceFixedBidParams($settings: [UpdatePriceFixedBidParams!]!) {
  getUpdatePriceFixedBidParams(settings: $settings) {
    description
    blob
    txID
    signers
    signature
    authAddress
  }
}