query GetSalesByCollection($id: String!, $offset: Int, $limit: Int) {
  getSalesByCollection(id: $id, offset: $offset, limit: $limit) {
    sales {
      saleType
      nftIndex
      appId
      currency
      unitPrice
      nNFTs
      totalPrice
      txIDs
      groupId
      sellerAddress
      royaltyAddres
      buyerAddress
      sellerShare
      royaltyShare
      managerShare
      round
      timestamp
      primary
      totalValue
      nft {
        token {
          index
        }
        info {
          title
          nsfw
        }
        media {
          fileroomId
          cid
          dimensions
          storageSize
          mimeType
          integrity
          previews {
            size
            cid
            mimeType
            integrity
          }
          thumbnail {
            fileroomId
            cid
            mimeType
            previews {
              size
              cid
              mimeType
            }
          }
        }
      }
    }
    pageInfo {
      totalDocs
      offset
      limit
      totalPages
      page
      hasPrevPage
      hasNextPage
      prevPage
      nextPage
    }
  }
}