query GetSalesByNFT($limit: Int, $index: Int!, $offset: Int) {
  getSalesByNFT(limit: $limit, index: $index, offset: $offset) {
    sales {
      saleType
      nftIndex
      appId
      currency
      unitPrice
      nNFTs
      totalPrice
      txIDs
      groupId
      sellerAddress
      royaltyAddres
      buyerAddress
      sellerShare
      royaltyShare
      managerShare
      round
      timestamp
      primary
      totalValue
    }
    pageInfo {
      totalDocs
      offset
      limit
      totalPages
      page
      hasPrevPage
      hasNextPage
      prevPage
      nextPage
    }
  }
}