export const itemsForSale = [
  {
    category: 'weapon',
    name: 'solar blade',
    collection: 'CGF',
    description: 'Harness the power of the sun with this advanced energy blade',
    seller: 'X9G5F3OQ2A3S8VH6BZPLKJ8RWNLPA2DVJXU7C5RKO6T4N9Y1ZM0Q',
    price: '2400.99',
    list_date: '25/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'robo-kitty',
    collection: 'B-Kartel',
    description:
      'A robotic kitty companion with customizable features and AI intelligence',
    seller: 'J7NQ3YVTU4H6XK5F2E8PL0C1AB2O9ZR6MWL3FDYK7SGX1AQBHKR8',
    price: '800.45',
    list_date: '28/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'lunar hoverboard',
    collection: 'MOO',
    description:
      'Zoom through the metaverse on this stylish lunar-inspired hoverboard',
    seller: 'H3P2I8G7L1U6R5F4E2L0C9A8B7O4R6W3NLPA2DVJXU7C5RKO',
    price: '1500.75',
    list_date: '27/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'neon ninja outfit',
    collection: 'Node Keepers',
    description:
      'Blend into the digital shadows with this futuristic neon ninja outfit',
    seller: 'K1J8RWNLPA2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPL',
    price: '1200.20',
    list_date: '26/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'quantum amulet',
    collection: 'Algoana',
    description: 'An ancient amulet with mysterious quantum powers',
    seller: 'SGTSMZXVHV34QDAHH7RDH226GLD55U34BLT6YP5L4AENCK6AVVGCOQM6XG',
    price: '1800.60',
    list_date: '24/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'furniture',
    name: 'phoenix wings',
    collection: 'CGF',
    description:
      'Elegant wings that grant you the majestic appearance of a phoenix',
    seller: 'U7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RWNLPA2DVJ',
    price: '2000.30',
    list_date: '23/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'furniture',
    name: 'virtual reality couch',
    collection: 'B-Kartel',
    description:
      'Experience unparalleled comfort while exploring the virtual realms',
    seller: '7RDH226GLD55U34BLT6YP5L4AENCK6AVVGCOQM6XGSGTSMZXVHV34QD',
    price: '400.85',
    list_date: '21/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'furniture',
    name: 'crypto-penguin',
    collection: 'MOO',
    description:
      'Adorable penguin pet that loves to dive into the blockchain waves',
    seller: 'O2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RW',
    price: '600.15',
    list_date: '20/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'plasma blaster',
    collection: 'Node Keepers',
    description:
      'Unleash devastating plasma blasts with this cutting-edge weapon',
    seller: 'NLPA2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RW',
    price: '2800.50',
    list_date: '19/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'plasma blaster',
    collection: 'Node Keepers',
    description:
      'Unleash devastating plasma blasts with this cutting-edge weapon',
    seller: 'NLPA2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RW',
    price: '2800.50',
    list_date: '19/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'plasma blaster',
    collection: 'Node Keepers',
    description:
      'Unleash devastating plasma blasts with this cutting-edge weapon',
    seller: 'NLPA2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RW',
    price: '2800.50',
    list_date: '19/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'lands',
    name: 'plasma blaster',
    collection: 'Node Keepers',
    description:
      'Unleash devastating plasma blasts with this cutting-edge weapon',
    seller: 'NLPA2DVJXU7C5RKO6T4N9Y1ZM0QX9G5F3OQ2A3S8VH6BZPLK1J8RW',
    price: '2800.50',
    list_date: '19/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'steampunk explorer',
    collection: 'Algoana',
    description:
      'Gear up as a steampunk explorer and traverse the metaverse in style',
    seller: 'GCOQM6XGSGTSMZXVHV34QDAHH7RDH226GLD55U34BLT6YP5L4AENCK6A',
    price: '1500.40',
    list_date: '18/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'steampunk explorer',
    collection: 'Algoana',
    description:
      'Gear up as a steampunk explorer and traverse the metaverse in style',
    seller: 'GCOQM6XGSGTSMZXVHV34QDAHH7RDH226GLD55U34BLT6YP5L4AENCK6A',
    price: '1500.40',
    list_date: '18/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'steampunk explorer',
    collection: 'Algoana',
    description:
      'Gear up as a steampunk explorer and traverse the metaverse in style',
    seller: 'GCOQM6XGSGTSMZXVHV34QDAHH7RDH226GLD55U34BLT6YP5L4AENCK6A',
    price: '1500.40',
    list_date: '18/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
  {
    category: 'outfit',
    name: 'steampunk explorer',
    collection: 'Algoana',
    description:
      'Gear up as a steampunk explorer and traverse the metaverse in style',
    seller: 'GCOQM6XGSGTSMZXVHV34QDAHH7RDH226GLD55U34BLT6YP5L4AENCK6A',
    price: '1500.40',
    list_date: '18/01/2024',
    image: '/img/marketplace_images/cgf_rxelms.jpg',
  },
];
